--[[
描述:		vc 项目生成模块
作者:		weiny zhou
创建日期:	2012-04-29
修改日期:	2012-04-29
版权:		版权所有，未经授权不得擅自拷贝复制或传播本代码的部分或全部.违者必究!
]]--

function vc_create_2008_vcproj(szFileName,szProject,szInclude,szDefine,szLibs)
	return vc_create_file_vcproj("9.00",szProject,szInclude,szDefine,szLibs);
end

function vc_create_2005_vcproj(szFileName,szProject,szInclude,szDefine,szLibs)
	return vc_create_file_vcproj("8.00",szProject,szInclude,szDefine,szLibs);
end
function vc_create_file_vcproj(ver,proname,includedir,define,libs)
	local szHead="<?xml version=\"1.0\" encoding=\"gb2312\"?>\n"..
"<VisualStudioProject\n"..
"	ProjectType=\"Visual C++\"\n"..
"	Version=\""..ver.."\"\n"..
"	Name=\""..proname.."\"\n"..
"	ProjectGUID=\"{EDA79E1D-5300-49D5-82F8-820C1656EE64}\"\n"..
"	RootNamespace=\""..proname.."\"\n"..
"	Keyword=\"Win32Proj\"\n "..
"	TargetFrameworkVersion=\"196613\"\n"..
"	>\n"..
"	<Platforms>\n"..
"		<Platform\n"..
"			Name=\"Win32\"\n"..
"		/>\n"..
"	</Platforms>\n"..
"	<ToolFiles>\n"..
"	</ToolFiles>\n"..
"	<Configurations>\n"..
"		<Configuration\n"..
"			Name=\"Debug|Win32\"\n"..
"			OutputDirectory=\"$(SolutionDir)$(ConfigurationName)\"\n"..
"			IntermediateDirectory=\"$(ConfigurationName)\"\n"..
"			ConfigurationType=\"2\"\n"..
"			CharacterSet=\"1\"\n"..
"			>\n"..
"			<Tool\n"..
"				Name=\"VCPreBuildEventTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCCustomBuildTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCXMLDataGeneratorTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCWebServiceProxyGeneratorTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCMIDLTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCCLCompilerTool\"\n"..
"				Optimization=\"0\"\n"..
"				AdditionalIncludeDirectories=\""..includedir.."\"\n"..
"				PreprocessorDefinitions=\"WIN32;_DEBUG;_DLL;HAVE_CONFIG_H=1"..define.."\"\n"..
"				MinimalRebuild=\"true\"\n"..
"				BasicRuntimeChecks=\"3\"\n"..
"				RuntimeLibrary=\"3\"\n"..
"				UsePrecompiledHeader=\"0\"\n"..
"				WarningLevel=\"3\"\n"..
"				DebugInformationFormat=\"4\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCManagedResourceCompilerTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCResourceCompilerTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCPreLinkEventTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCLinkerTool\"\n"..
"				AdditionalDependencies=\""..libs.."\"\n"..
"				GenerateDebugInformation=\"true\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCALinkTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCManifestTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCXDCMakeTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCBscMakeTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCFxCopTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCAppVerifierTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCPostBuildEventTool\"\n"..
"			/>\n"..
"		</Configuration>\n"..
"		<Configuration\n"..
"			Name=\"Release|Win32\"\n"..
"			OutputDirectory=\"$(SolutionDir)$(ConfigurationName)\"\n"..
"			IntermediateDirectory=\"$(ConfigurationName)\"\n"..
"			ConfigurationType=\"2\"\n"..
"			CharacterSet=\"1\"\n"..
"			WholeProgramOptimization=\"1\"\n"..
"			>\n"..
"			<Tool\n"..
"				Name=\"VCPreBuildEventTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCCustomBuildTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCXMLDataGeneratorTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCWebServiceProxyGeneratorTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCMIDLTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCCLCompilerTool\"\n"..
"				Optimization=\"2\"\n"..
"				InlineFunctionExpansion=\"2\"\n"..
"				EnableIntrinsicFunctions=\"true\"\n"..
"				AdditionalIncludeDirectories=\""..includedir.."\"\n"..
"				PreprocessorDefinitions=\"WIN32;NDEBUG;_DLL;HAVE_CONFIG_H=1"..define.."\"\n"..
"				RuntimeLibrary=\"2\"\n"..
"				EnableFunctionLevelLinking=\"true\"\n"..
"				UsePrecompiledHeader=\"0\"\n"..
"				WarningLevel=\"3\"\n"..
"				DebugInformationFormat=\"0\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCManagedResourceCompilerTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCResourceCompilerTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCPreLinkEventTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCLinkerTool\"\n"..
"				AdditionalDependencies=\""..libs.."\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCALinkTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCManifestTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCXDCMakeTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCBscMakeTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCFxCopTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCAppVerifierTool\"\n"..
"			/>\n"..
"			<Tool\n"..
"				Name=\"VCPostBuildEventTool\"\n"..
"			/>\n"..
"		</Configuration>\n"..
"	</Configurations>\n"..
"	<References>\n"..
"	</References>\n"..
"	<Files>\n";
local szEnd=
"		<Filter\n"..
"			Name=\"headers\"\n"..
"			Filter=\"cpp;c;cc;cxx;def;odl;idl;hpj;bat;asm;asmx\"\n"..
"			UniqueIdentifier=\"{4FC737F1-C7A5-4376-A066-2A32D752A2FF}\"\n"..
"			>\n"..
"		</Filter>\n"..
"		<Filter\n"..
"			Name=\"sources\"\n"..
"			Filter=\"h;hpp;hxx;hm;inl;inc;xsd\"\n"..
"			UniqueIdentifier=\"{93995380-89BD-4b04-88EB-625FBE52EBFB}\"\n"..
"			>\n"..
"		</Filter>\n"..
"		<Filter\n"..
"			Name=\"resources\"\n"..
"			Filter=\"rc;ico;cur;bmp;dlg;rc2;rct;bin;rgs;gif;jpg;jpeg;jpe;resx;tiff;tif;png;wav\"\n"..
"			UniqueIdentifier=\"{67DA6AB6-F800-4c08-8B7A-83BB121AAD01}\"\n"..
"			>\n"..
"		</Filter>\n"..
"	</Files>\n"..
"	<Globals>\n"..
"	</Globals>\n"..
"</VisualStudioProject>\n"
;
return szHead,szEnd;
end